// Code generated by Slice Machine. DO NOT EDIT.

import type * as prismicT from "@prismicio/types";
import type * as prismic from "@prismicio/client";

type Simplify<T> = {
    [KeyType in keyof T]: T[KeyType];
};
/** Content for Component documents */
interface ComponentDocumentData {
    /**
     * Name field in *Component*
     *
     * - **Field Type**: Text
     * - **Placeholder**: *None*
     * - **API ID Path**: component.name
     * - **Tab**: Main
     * - **Documentation**: https://prismic.io/docs/core-concepts/key-text
     *
     */
    name: prismicT.KeyTextField;
    /**
     * Description field in *Component*
     *
     * - **Field Type**: Text
     * - **Placeholder**: *None*
     * - **API ID Path**: component.description
     * - **Tab**: Main
     * - **Documentation**: https://prismic.io/docs/core-concepts/key-text
     *
     */
    description: prismicT.KeyTextField;
    /**
     * Code examples field in *Component*
     *
     * - **Field Type**: Rich Text
     * - **Placeholder**: *None*
     * - **API ID Path**: component.code_examples
     * - **Tab**: Main
     * - **Documentation**: https://prismic.io/docs/core-concepts/rich-text-title
     *
     */
    code_examples: prismicT.RichTextField;
    /**
     * Props field in *Component*
     *
     * - **Field Type**: Group
     * - **Placeholder**: *None*
     * - **API ID Path**: component.props[]
     * - **Tab**: Main
     * - **Documentation**: https://prismic.io/docs/core-concepts/group
     *
     */
    props: prismicT.GroupField<Simplify<ComponentDocumentDataPropsItem>>;
}
/**
 * Item in Component → Props
 *
 */
export interface ComponentDocumentDataPropsItem {
    /**
     * Prop field in *Component → Props*
     *
     * - **Field Type**: Content Relationship
     * - **Placeholder**: *None*
     * - **API ID Path**: component.props[].prop
     * - **Documentation**: https://prismic.io/docs/core-concepts/link-content-relationship
     *
     */
    prop: prismicT.RelationField<"prop" | "mixin_group">;
}
/**
 * Component document from Prismic
 *
 * - **API ID**: `component`
 * - **Repeatable**: `true`
 * - **Documentation**: https://prismic.io/docs/core-concepts/custom-types
 *
 * @typeParam Lang - Language API ID of the document.
 */
export type ComponentDocument<Lang extends string = string> = prismicT.PrismicDocumentWithUID<Simplify<ComponentDocumentData>, "component", Lang>;
/** Content for Input documents */
interface InputDocumentData {
    /**
     * Name field in *Input*
     *
     * - **Field Type**: Text
     * - **Placeholder**: *None*
     * - **API ID Path**: input.name
     * - **Tab**: Main
     * - **Documentation**: https://prismic.io/docs/core-concepts/key-text
     *
     */
    name: prismicT.KeyTextField;
    /**
     * Description field in *Input*
     *
     * - **Field Type**: Text
     * - **Placeholder**: *None*
     * - **API ID Path**: input.description
     * - **Tab**: Main
     * - **Documentation**: https://prismic.io/docs/core-concepts/key-text
     *
     */
    description: prismicT.KeyTextField;
}
/**
 * Input document from Prismic
 *
 * - **API ID**: `input`
 * - **Repeatable**: `true`
 * - **Documentation**: https://prismic.io/docs/core-concepts/custom-types
 *
 * @typeParam Lang - Language API ID of the document.
 */
export type InputDocument<Lang extends string = string> = prismicT.PrismicDocumentWithUID<Simplify<InputDocumentData>, "input", Lang>;
/** Content for Mixin Group documents */
interface MixinGroupDocumentData {
    /**
     * Name field in *Mixin Group*
     *
     * - **Field Type**: Text
     * - **Placeholder**: *None*
     * - **API ID Path**: mixin_group.name
     * - **Tab**: Main
     * - **Documentation**: https://prismic.io/docs/core-concepts/key-text
     *
     */
    name: prismicT.KeyTextField;
    /**
     * Props field in *Mixin Group*
     *
     * - **Field Type**: Group
     * - **Placeholder**: *None*
     * - **API ID Path**: mixin_group.props[]
     * - **Tab**: Main
     * - **Documentation**: https://prismic.io/docs/core-concepts/group
     *
     */
    props: prismicT.GroupField<Simplify<MixinGroupDocumentDataPropsItem>>;
    /**
     * Slice Zone field in *Mixin Group*
     *
     * - **Field Type**: Slice Zone
     * - **Placeholder**: *None*
     * - **API ID Path**: mixin_group.slices[]
     * - **Tab**: Main
     * - **Documentation**: https://prismic.io/docs/core-concepts/slices
     *
     */
    slices: prismicT.SliceZone<MixinGroupDocumentDataSlicesSlice>;
}
/**
 * Item in Mixin Group → Props
 *
 */
export interface MixinGroupDocumentDataPropsItem {
    /**
     * Prop field in *Mixin Group → Props*
     *
     * - **Field Type**: Content Relationship
     * - **Placeholder**: *None*
     * - **API ID Path**: mixin_group.props[].prop
     * - **Documentation**: https://prismic.io/docs/core-concepts/link-content-relationship
     *
     */
    prop: prismicT.RelationField<"prop">;
}
/**
 * Slice for *Mixin Group → Slice Zone*
 *
 */
type MixinGroupDocumentDataSlicesSlice = never;
/**
 * Mixin Group document from Prismic
 *
 * - **API ID**: `mixin_group`
 * - **Repeatable**: `true`
 * - **Documentation**: https://prismic.io/docs/core-concepts/custom-types
 *
 * @typeParam Lang - Language API ID of the document.
 */
export type MixinGroupDocument<Lang extends string = string> = prismicT.PrismicDocumentWithUID<Simplify<MixinGroupDocumentData>, "mixin_group", Lang>;
/** Content for Prop documents */
interface PropDocumentData {
    /**
     * Name field in *Prop*
     *
     * - **Field Type**: Text
     * - **Placeholder**: *None*
     * - **API ID Path**: prop.name
     * - **Tab**: Main
     * - **Documentation**: https://prismic.io/docs/core-concepts/key-text
     *
     */
    name: prismicT.KeyTextField;
    /**
     * Description field in *Prop*
     *
     * - **Field Type**: Text
     * - **Placeholder**: *None*
     * - **API ID Path**: prop.description
     * - **Tab**: Main
     * - **Documentation**: https://prismic.io/docs/core-concepts/key-text
     *
     */
    description: prismicT.KeyTextField;
    /**
     * Inputs field in *Prop*
     *
     * - **Field Type**: Group
     * - **Placeholder**: *None*
     * - **API ID Path**: prop.inputs[]
     * - **Tab**: Main
     * - **Documentation**: https://prismic.io/docs/core-concepts/group
     *
     */
    inputs: prismicT.GroupField<Simplify<PropDocumentDataInputsItem>>;
    /**
     * Responsive field in *Prop*
     *
     * - **Field Type**: Boolean
     * - **Placeholder**: *None*
     * - **Default Value**: false
     * - **API ID Path**: prop.responsive
     * - **Tab**: Main
     * - **Documentation**: https://prismic.io/docs/core-concepts/boolean
     *
     */
    responsive: prismicT.BooleanField;
}
/**
 * Item in Prop → Inputs
 *
 */
export interface PropDocumentDataInputsItem {
    /**
     * Input field in *Prop → Inputs*
     *
     * - **Field Type**: Content Relationship
     * - **Placeholder**: *None*
     * - **API ID Path**: prop.inputs[].input
     * - **Documentation**: https://prismic.io/docs/core-concepts/link-content-relationship
     *
     */
    input: prismicT.RelationField<"input">;
}
/**
 * Prop document from Prismic
 *
 * - **API ID**: `prop`
 * - **Repeatable**: `true`
 * - **Documentation**: https://prismic.io/docs/core-concepts/custom-types
 *
 * @typeParam Lang - Language API ID of the document.
 */
export type PropDocument<Lang extends string = string> = prismicT.PrismicDocumentWithUID<Simplify<PropDocumentData>, "prop", Lang>;
export type AllDocumentTypes = ComponentDocument | InputDocument | MixinGroupDocument | PropDocument;
declare module "@prismicio/client" {
    interface CreateClient {
        (repositoryNameOrEndpoint: string, options?: prismic.ClientConfig): prismic.Client<AllDocumentTypes>;
    }
    namespace Content {
        export type { ComponentDocumentData, ComponentDocumentDataPropsItem, ComponentDocument, InputDocumentData, InputDocument, MixinGroupDocumentData, MixinGroupDocumentDataPropsItem, MixinGroupDocumentDataSlicesSlice, MixinGroupDocument, PropDocumentData, PropDocumentDataInputsItem, PropDocument, AllDocumentTypes };
    }
}
